version: 0.1

phases:
  # build:
  #   commands:
  #     - npm install
  #     - npm run build
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - pwd
      - ls src
      - ls src/components
      - npm run build

artifacts:
  files:
    - "**/*"
  # base-directory: build
  discard-paths: yes
